// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using STSys.Core.Data.Context;

namespace STSys.Core.Data.Context.Migrations
{
    [DbContext(typeof(STSysContext))]
    [Migration("20191010004157_20191010")]
    partial class _20191010
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("STSys.Core.Users.Abstractions.Entities.ManagerEntities", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<string>("Account");

                    b.Property<string>("Address");

                    b.Property<string>("Content");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<string>("Email");

                    b.Property<string>("Encrypt");

                    b.Property<DateTime?>("LastTime");

                    b.Property<string>("Mobile");

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.Property<string>("PicUrl");

                    b.Property<string>("QQ");

                    b.Property<int?>("Status");

                    b.HasKey("Id");

                    b.ToTable("Manager");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1e6856e-28c7-4e12-88cc-d451707b5e80"),
                            Account = "xxtk",
                            Address = "重庆",
                            CreateTime = new DateTime(2019, 10, 10, 8, 41, 57, 230, DateTimeKind.Local).AddTicks(4468),
                            Email = "xxtk@163.com",
                            Encrypt = "123",
                            Mobile = "13512341234",
                            Name = "张三",
                            Password = "123qwe",
                            PicUrl = "",
                            QQ = "123456",
                            Status = 0
                        });
                });

            modelBuilder.Entity("STSys.Core.Users.Abstractions.Entities.UsersEntities", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CreateTime");

                    b.Property<string>("Email");

                    b.Property<string>("Encrypt");

                    b.Property<string>("Mobile");

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.Property<string>("PicUrl");

                    b.Property<decimal?>("Price");

                    b.Property<int>("Status");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("users");
                });
#pragma warning restore 612, 618
        }
    }
}
