// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using STSys.Core.Data.Context;

namespace STSys.Core.Data.Context.Migrations
{
    [DbContext(typeof(STSysContext))]
    partial class STSysContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("STSys.Core.Admin.Abstractions.Entities.ColumnEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ColumnEName");

                    b.Property<string>("ColumnName");

                    b.Property<int?>("ColumnType");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<int?>("DataSource");

                    b.Property<string>("Intro");

                    b.Property<int?>("Sort");

                    b.Property<int?>("Source");

                    b.Property<int?>("Status");

                    b.Property<string>("Tab");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.ToTable("Column");
                });

            modelBuilder.Entity("STSys.Core.Admin.Abstractions.Entities.IndexRecommendEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CategoryId");

                    b.Property<int?>("ColumnId");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<string>("Img");

                    b.Property<string>("Intro");

                    b.Property<string>("Name");

                    b.Property<decimal?>("Price");

                    b.Property<int?>("ProId");

                    b.Property<int?>("ProvinceId");

                    b.Property<int?>("Sort");

                    b.Property<int?>("Status");

                    b.Property<Guid?>("TabId");

                    b.Property<short>("Type");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.ToTable("Recommend");
                });

            modelBuilder.Entity("STSys.Core.Users.Abstractions.Entities.ManagerEntities", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<string>("Account");

                    b.Property<string>("Address");

                    b.Property<string>("Content");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<string>("Email");

                    b.Property<string>("Encrypt");

                    b.Property<DateTime?>("LastTime");

                    b.Property<string>("Mobile");

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.Property<string>("PicUrl");

                    b.Property<string>("QQ");

                    b.Property<int?>("Status");

                    b.HasKey("Id");

                    b.ToTable("Manager");

                    b.HasData(
                        new
                        {
                            Id = new Guid("26e5e86e-2efc-48c9-aad0-9d1f70327057"),
                            Account = "xxtk",
                            Address = "重庆",
                            CreateTime = new DateTime(2019, 10, 16, 14, 28, 35, 424, DateTimeKind.Local).AddTicks(6062),
                            Email = "xxtk@163.com",
                            Encrypt = "123",
                            Mobile = "13512341234",
                            Name = "张三",
                            Password = "CBC33BED3530501DCE65D6FD65C669222A0EDA521A56E3B90489E71FB3EE142E",
                            PicUrl = "",
                            QQ = "123456",
                            Status = 0
                        });
                });

            modelBuilder.Entity("STSys.Core.Users.Abstractions.Entities.UsersEntities", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CreateTime");

                    b.Property<string>("Email");

                    b.Property<string>("Encrypt");

                    b.Property<string>("Mobile");

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.Property<string>("PicUrl");

                    b.Property<decimal?>("Price");

                    b.Property<int>("Status");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
